/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package data;
import tools.DBconnection;
import javax.swing.table.DefaultTableModel;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import tools.Function;

public class Form_TipeKendaraan extends javax.swing.JFrame {
    
    DefaultTableModel tblmodel;
    Connection conn;
    String arr[] = {"id_tipe_kendaraan","tipe_kendaraan"}, nama_table = "tipe_kendaraan";
    Function function = new Function();
    
    public Form_TipeKendaraan() {
        initComponents();
        setResizable(false);
        DBconnection openconn = new DBconnection();
        this.conn = openconn.create_connection();
        this.tblmodel = (DefaultTableModel)TblTipeKendaraan.getModel();
        function.load_table(tblmodel, arr, nama_table);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblTipeKendaraan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtTipeKendaraan = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnBack = new javax.swing.JToggleButton();
        TxtIDTerpilih = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        jDesktopPane1.setBackground(new java.awt.Color(222, 229, 235));

        TblTipeKendaraan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "TIPE KENDARAAN"
            }
        ));
        TblTipeKendaraan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblTipeKendaraanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TblTipeKendaraan);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Vehicles Types");

        jLabel2.setText("Tipe Kendaraan");

        TxtTipeKendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTipeKendaraanActionPerformed(evt);
            }
        });

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        TxtIDTerpilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtIDTerpilihActionPerformed(evt);
            }
        });

        jLabel3.setText("Vehicle ID");

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(TxtTipeKendaraan, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnTambah, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnBack, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(TxtIDTerpilih, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnEdit, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnDelete, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(TxtTipeKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTambah))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                    .addComponent(btnEdit)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDelete))
                                .addComponent(TxtIDTerpilih, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25))))
        );

        jDesktopPane1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {TxtIDTerpilih, TxtTipeKendaraan});

        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtTipeKendaraan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtIDTerpilih, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTambah, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEdit, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(12, 12, 12))
        );

        jDesktopPane1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {TxtIDTerpilih, TxtTipeKendaraan});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed

        /* 
            -- add button function
                -- take ( table_name, field_name, and data_field ) as an argument
        */
        
        String arr[] = {"tipe_kendaraan"};
        String arr2[] = {"'"+TxtTipeKendaraan.getText()+"'"};
        function.add_table(nama_table, arr, arr2);
        function.load_table(tblmodel, this.arr, nama_table);
          
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        
        /* 
            -- Update button function
                -- take ( table name, array field command, primary key) as an argument
        */
        
        String[] arr = { "tipe_kendaraan='" + TxtTipeKendaraan.getText()+"'"};
        int konfirmasi_update = JOptionPane.showConfirmDialog(null, "Apakah Ingin Update Tipe kendaraan " + TxtIDTerpilih.getText());
        
        if (konfirmasi_update == 0){
            JOptionPane.showMessageDialog(this, "Tipe Kendaraan " + TxtIDTerpilih.getText() + " Terupdate");
            function.update_table(nama_table, arr, "id_tipe_kendaraan='"+TxtIDTerpilih.getText()+"'");
            function.load_table(tblmodel, this.arr, nama_table);
            resetInput();
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        
        /* 
        Delete Function usage
            -- this function will pass arguments to tools function
                -- delete argument must filled with ( table_name, field + primary key ) 
        */
        
        int konfirmasi_delete = JOptionPane.showConfirmDialog(this, "ID Tipe Kendaraan " + TxtIDTerpilih.getText() + " Terhapus");
        if (konfirmasi_delete == 0){
                
                JOptionPane.showMessageDialog(this, "ID Tipe Kendaraan " + TxtIDTerpilih.getText() + " Terhapus");
                function.delete_table(nama_table, "id_tipe_kendaraan=" + TxtIDTerpilih.getText());
                function.load_table(tblmodel, arr, nama_table);
                resetInput();
            }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
       
        /* 
            -- dispose all generated component
                -- set form menu visilbility to TRUE
        */
        
        dispose();
        MenuAdmin menu = new MenuAdmin();
        menu.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void TxtIDTerpilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIDTerpilihActionPerformed
        
    }//GEN-LAST:event_TxtIDTerpilihActionPerformed

    private void TxtTipeKendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTipeKendaraanActionPerformed
    
    }//GEN-LAST:event_TxtTipeKendaraanActionPerformed

    private void TblTipeKendaraanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblTipeKendaraanMouseClicked
        
        /* 
        MouseClicked Action Table Function usage
            -- this function will set all textbox with current clicked data
                -- this function takes primary key to get data
        */
        
        int column = TblTipeKendaraan.getSelectedColumn(), row = TblTipeKendaraan.getSelectedRow();
        String select = (String) TblTipeKendaraan.getValueAt(row, 0);
        TxtIDTerpilih.setText(select);
        
       try
        {
            String sql = "SELECT * FROM tipe_kendaraan where id_tipe_kendaraan = " + select;
            DBconnection.create_connection().createStatement();
            ResultSet result = DBconnection.create_connection().createStatement().executeQuery(sql);
            
            while (result.next()){
                TxtTipeKendaraan.setText(result.getString(2));
            }
        } catch (SQLException e) { System.out.println(e); }
       
    }//GEN-LAST:event_TblTipeKendaraanMouseClicked
 
    public void resetInput(){
        String t = "";
        TxtTipeKendaraan.setText(t);
        TxtIDTerpilih.setText(t);
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TblTipeKendaraan;
    private javax.swing.JTextField TxtIDTerpilih;
    private javax.swing.JTextField TxtTipeKendaraan;
    private javax.swing.JToggleButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnTambah;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
